CREATE TABLE IF NOT EXISTS message (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payload TEXT,
  receivedAt TIMESTAMP
);

CREATE TABLE IF NOT EXISTS partner(
  id INT AUTO_INCREMENT PRIMARY KEY,
  alias VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  direction VARCHAR(255) NOT NULL,
  application VARCHAR(255),
  processedFlowType VARCHAR(255) NOT NULL,
  description VARCHAR(1000) NOT NULL
);
 
CREATE QLOCAL (QUEUE('MY_QUEUE') TYPE(LOCAL) INITIATOR(ANY))